cobnb/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from cobnb import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url('', include('users.urls', namespace='users')),
    url('', include('places.urls', namespace='places')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

places/urls.py
from django.conf.urls import include, url
from places.views import ListPlace, CreatePlace, PlaceDetail

urlpatterns = [

    url(r'^list_place/',
        ListPlace.as_view(),
        name='home'),

    url(r'^create_place/$',
        CreatePlace.as_view(),
        name='new_place'),

    url(r'^place_detail/(?P<pk>[0-9]+)',
        PlaceDetail.as_view(),
        name='place_detail'),

]

users/urls.py
from django.conf.urls import include, url
from users.views import UserLogin, UserCreate

urlpatterns = [

    url(r'^signin/$',
        UserLogin.as_view(),
        name='sigin'),
    url(r'^signup/$',
        UserCreate.as_view(),
        name='signup'),
    url(r'^logout/$', 'users.views.logout_view', name='logout'),

]

API/models.py
from django.db import models

# Create your models here.

places/models.py
from django.db import models
from django.contrib.auth.models import User
from users.models import UserProfile


CHOICE_PLACES = (
    ('F', 'Food'),
    ('T', 'Technologic'),
    ('M', 'Medicin'),
    ('S', 'School'),
)

CHOICE_PAYOUT = (
    ('D', 'Tarjeta de Debito'),
    ('C', 'Tarjeta de Credito'),
    ('E', 'Efectivo'),
    ('P', 'PayPal'),
)


class Place(models.Model):

    owner = models.ForeignKey(User, null=True, blank=True)

    # Place's Address
    city = models.CharField(max_length=255)
    number = models.CharField(max_length=10)
    state = models.CharField(max_length=255)
    street = models.CharField(max_length=255)
    zip_code = models.CharField(max_length=8)

    # Meta Data
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    # Image
    place_image = models.ImageField(upload_to="static/img/place_media", null=True, blank=True)

    # Money
    price = models.FloatField(default=0.0)
    payout_method = models.CharField(max_length=2225, choices=CHOICE_PAYOUT, null=True, blank=True)

    # Place's Attributes
    name = models.CharField(max_length=1000, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    meters = models.IntegerField(default=0)
    type_of_place = models.CharField(max_length=255, choices=CHOICE_PLACES, null=True, blank=True)

    # Available
    place_available = models.BooleanField(default=True)

    def get_image(self):
        try:
            return u'<img src="%s" style="display: block; width: 60px;"/>' % self.place_image.url
        except:
            return "<h3>No image</h3>"
    get_image.allow_tags = True

users/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):
    user = models.OneToOneField(User)

places/forms.py
from django.forms import ModelForm
from places.models import Place


class PlaceForm(ModelForm):
    def save(self, user=None):
        self.instance.owner = user
        super(PlaceForm, self).save()

    class Meta:
        model = Place
        fields = ['name',
                  'price',
                  'type_of_place',
                  'description',
                  'meters',
                  'place_image', ]
# @gabocharles wairamexico

API/views.py
from django.shortcuts import render

# Create your views here.

places/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from places.models import Place
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import TemplateView, ListView, DetailView
from users.models import UserProfile
from django.contrib.auth.models import User


class ListPlace(ListView):
    model = Place
    template_name = "place_list.html"


class CreatePlace(CreateView):
    model = Place
    template_name = "place_form.html"
    fields = ['name',
              'price',
              'type_of_place',
              'description',
              'meters',
              'place_image', ]

    success_url = '/list_place'

    @method_decorator(login_required(login_url="/signin/"))
    def dispatch(self, *args, **kwargs):
        return super(CreatePlace, self).dispatch(*args, **kwargs)

    def form_valid(self, form):
        user_django = User.objects.get(id=self.request.user.id)
        form.instance.owner = user_django
        return super(CreatePlace, self).form_valid(form)


class PlaceDetail(DetailView):
    model = Place
    template_name = "place_detail.html"

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(PlaceDetail, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(PlaceDetail, self).get_context_data(**kwargs)
        return context

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from users.models import UserProfile
from django.contrib.auth.models import User
from django.views.generic.edit import CreateView, UpdateView, FormView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView, ListView
from django.contrib.auth.forms import AuthenticationForm
from django.core.urlresolvers import reverse_lazy
from places.forms import PlaceForm
from places.models import Place


class UserLogin(FormView):
    form_class = AuthenticationForm
    template_name = "signin.html"
    success_url = "/list_place"

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return redirect(self.get_success_url())
        else:
            return super(UserLogin, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        login(self.request, form.get_user())
        return super(UserLogin, self).form_valid(form)


class UserCreate(CreateView):
    model = User
    template_name = "user_form.html"
    form = PlaceForm
    fields = ['first_name',
              'last_name',
              'email',
              'username',
              'password', ]

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        obj.set_password(form.cleaned_data['password'])
        obj.save()
        return redirect("/signin")


def logout_view(request):
    logout(request)
    return redirect('/')

places/templates/create_place.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Create Place</title>
</head>
<body>
	<form method="POST" action = "{%url 'places:new_place'%}">
		{% csrf_token %}
		{{ place_form.as_p }}
		<input type="submit">
	</form>
</body>
</html>

places/templates/place_detail.html
<!DOCTYPE html>
<html>
<head>
    <title>Details</title>
</head>
<body>
    <h1>{{ place.nombre}}</h1>
    <h3>Owner Place: {{ place.owner }}</h3>
    <figure>
        {% if place.place_image %}
        <img src="{{ place.place_image.url }}">
        {% else %}
        <img src="http://www.404notfound.fr/assets/images/pages/img/androiddev101.jpg">
        {% endif %}
    </figure>
    <p>{{ place.description}}</p>
    <h3>Precio: ${{ place.price }}</h3>
</body>
</html>

places/templates/place_form.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Create Place</title>
</head>
<body>
	<form method="POST" action = "" enctype="multipart/form-data" >
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit">
	</form>
</body>
</html>

places/templates/place_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
<body>
    <h2>Places</h2>
    <ul>
        {% for place in object_list %}
            <li>Name: {{ place.name }} | 
            Type: {{ place.type }} | 
            Price: {{ place.price }} |</li>
            Description: {{ place.description}}</li>
            <a href="{% url 'places:place_detail' place.id %}">Details</a>
        {% endfor %}
    </ul>
    <a href="/create_place">Create a new place</a>
    <a href="/logout">Logout</a>
</body>
</html>

places/templates/product_detail.html
<!DOCTYPE html>
<html>
<head>
    <title>Details</title>
</head>
<body>
    <h1>{{ place.nombre}}</h1>
    <h3>Owner Place: {{ place.owner }}</h3>
    <p>{{ place.description}}</p>
    {# <figure>
        {% if place.imagen %}
        <img src="{{ place.imagen.url }}">
        {% else %}
        <img src="http://www.404notfound.fr/assets/images/pages/img/androiddev101.jpg">
        {% endif %}
    </figure> #}
    <h3>Precio: ${{ place.price }}</h3>
</body>
</html>

users/templates/signin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sign In</title>
</head>
<body>
    {% if message %}
        <p>{{ message }}</p>
    {% endif %}
    <form action="" method="post">
        {% csrf_token %}
        <input type="text" placeholder="Username" name="username" />
        <input type="password" placeholder="Password" name="password" />
        <input type="submit" value="Sign In" />
    </form>
    <p>
        Create an account <a href="/signup">here.</a>
    </p>
</body>
</html>

users/templates/user_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create User</title>
</head>
<body>
    <form method="POST" action = "{%url 'users:signup'%}">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit">
    </form>
</body>
</html>